name: github pages

# on:
#   push:
#     branches:
#       - main  # Set a branch to deploy
#   pull_request:

on:
  push

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build Site
        run: |
          npm install
          hugo --environment "production" --minify
      
      # - name: Configure custom domain
      #   run: |
      #     # Copy CNAME file to the generated public folder
      #     # This is needed for the "gh-pages" branch to properly point to the custom domain
      #     cp CNAME doc/site/public

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/site/public